### ISSUE TITLE
[FEATURE REQUEST] Option to log in with a default user

### ISSUE THREAD

**Issue by Masacaai** [timberhill/lightdm-webkit2-monoarch#1]
Hey there!
I love your theme for lightdm, and I was wondering if there was a way to be able to log in with a default user.
Basically, instead of having to type in both user and password, you would only have to type in the password because the greeter automatically uses a certain username.

I feel like it should be pretty easy to do, considering all that would be required is to skip the username while logging in.
I would try a hand at implementing it myself, but I'm a complete noob at Javascript.  If you don't feel like this feature request particularly interests you, that's okay too, I'll just learn Javascript and implement it myself!

**Comment by timberhill** [comment]
Hi :wave: 
This looks like a good idea, will see if I have some time this week!

**Comment by timberhill** [comment]
Hi again @Masacaai, I have raised the pull request, feel free to pull the branch and have a look.

If the default user is set in `main.js`, the prompt will ask for the password straight away and show the username the password is for. It also checks if the user actually exists to prevent typos in a username from locking you out. If `defaultUser` is null or empty the behavior is the same as before.

**Comment by timberhill** [comment]
I have also refactored the code, so the diff is a mess there.

**Comment by Masacaai** [comment]
I just checked it out, and it works great! Thank you so much!
